// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/markovmix.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// split_seq
List split_seq(const List& seq_list, size_t len);
static SEXP _markovmix_split_seq_try(SEXP seq_listSEXP, SEXP lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const List& >::type seq_list(seq_listSEXP);
    Rcpp::traits::input_parameter< size_t >::type len(lenSEXP);
    rcpp_result_gen = Rcpp::wrap(split_seq(seq_list, len));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _markovmix_split_seq(SEXP seq_listSEXP, SEXP lenSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_markovmix_split_seq_try(seq_listSEXP, lenSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// colsums_by_group
NumericMatrix colsums_by_group(const List& value_list, size_t n_col);
static SEXP _markovmix_colsums_by_group_try(SEXP value_listSEXP, SEXP n_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const List& >::type value_list(value_listSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_col(n_colSEXP);
    rcpp_result_gen = Rcpp::wrap(colsums_by_group(value_list, n_col));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP _markovmix_colsums_by_group(SEXP value_listSEXP, SEXP n_colSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(_markovmix_colsums_by_group_try(value_listSEXP, n_colSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    bool rcpp_isLongjump_gen = Rcpp::internal::isLongjumpSentinel(rcpp_result_gen);
    if (rcpp_isLongjump_gen) {
        Rcpp::internal::resumeJump(rcpp_result_gen);
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int _markovmix_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("List(*split_seq)(const List&,size_t)");
        signatures.insert("NumericMatrix(*colsums_by_group)(const List&,size_t)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _markovmix_RcppExport_registerCCallable() { 
    R_RegisterCCallable("markovmix", "_markovmix_split_seq", (DL_FUNC)_markovmix_split_seq_try);
    R_RegisterCCallable("markovmix", "_markovmix_colsums_by_group", (DL_FUNC)_markovmix_colsums_by_group_try);
    R_RegisterCCallable("markovmix", "_markovmix_RcppExport_validate", (DL_FUNC)_markovmix_RcppExport_validate);
    return R_NilValue;
}

static const R_CallMethodDef CallEntries[] = {
    {"_markovmix_split_seq", (DL_FUNC) &_markovmix_split_seq, 2},
    {"_markovmix_colsums_by_group", (DL_FUNC) &_markovmix_colsums_by_group, 2},
    {"_markovmix_RcppExport_registerCCallable", (DL_FUNC) &_markovmix_RcppExport_registerCCallable, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_markovmix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
