# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

split_seq <- function(seq_list, len) {
    .Call(`_markovmix_split_seq`, seq_list, len)
}

colsums_by_group <- function(value_list, n_col) {
    .Call(`_markovmix_colsums_by_group`, value_list, n_col)
}

